### ISSUE TITLE
Strange issue with WhatIsThis plugin

### ISSUE THREAD

**Issue by kencinder** [nikosgram13/Gringotts#88]
**Describe the bug**
With Gringotts present, any combination of plugins it seems that is over 48 plugins, causes WhatIsThis to not display custom block names.

See https://github.com/steve4744/WhatIsThis/issues/6

**To Reproduce**

Install Gringots 2.12.2 on a 1.18.1 Paper server with WhatIsThis and Nova, and 47+ other plugins of your choosing. Custom Block Names from Nova will no longer display.
Depending on the plugins, may require more than 50...in my testing, 49 of any of the ones I use was enough to cause the issue.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Server Type: Paper
 - Server Version: 1.18.1-212
 - Gringotts Version: 2.12.2

**Additional context**

**Comment by steve4744** [comment]
With > 48 plugins (including Gringotts) the load order is getting changed, so that although Nova and Slimefun are soft-depends for WhatIsThis, they are being loaded after WhatIsThis, so its not aware of those plugins or custom blocks.

This is similar to #84 - the workaround provided by SkytAsul also seems to work for this issue.
